### ISSUE TITLE
How it work

### ISSUE THREAD

**Issue by radeonxy** [BeChris100/osintgram4j#4] opened 2024-02-18 18:30 UTC
i tried to find the .java file to run it after installation, i wonder if there any instruction how to run the tool thank u

**Comment by BeChris100** [comment] 2024-02-18 21:21
Hello.

I can give you a quick instruction on how to run it. Please do note that this project is still in the development stages.

The current requirement for building this project is to have a Linux environment prepared. You can do so by using a VM, a Cloud Instance (Google Cloud Shell, Linode, self-hosted etc.), within a Container, or within the WSL (Windows Subsystem for Linux). VM, Cloud and WSL are the recommended ones, since Containers might not have the necessary libraries to build.

I assume that you have already cloned the repository. If not, then you can do `git clone https://github.com/BeChris100/osintgram4j.git`.

From there, you run the `setup.sh` and `build.sh`. If there are errors regarding missing tools (e.g. missing `gcc`), you can install by doing `sudo apt install build-essential`, which will install the needed ones. This does not include `cmake`, so you would have to do `sudo apt install cmake`. Make sure that commands like `tar` and `wget` are also present.

If there is a successful build, and you can successfully run the project that is located as a binary under `out/pkg/osintgram4j/bin/osintgram4j`, then the build was successful. If there were errors during the build, I suggest copying the logs and log everything that is needed to reproduce the error. This way, the error will be fixed seamlessly.

However, if you want to build it for Windows, then you might need to modify the `CMakeLists.txt` within the `cxx` folder, and get the native libraries to be compiled. Since I do not use Windows, I have used the name prefixes that were compatible with Linux directly, which can be installed as a `mingw` package. The full package names are unknown to me, but they exist somewhere. Quick Google searches will help you out. Once the manual compilation for the native libraries were done, you can either run `jpackage` directly, or run `jdeps`, `jlink` and `jpackage` manually. They share a somewhat similar syntax, as they are being used in the `build.sh` script.

And to directly answer your question, you won't be able to directly run Java code, since it needs its specific class paths. The `jpackage` tool will help you eliminate this problem. Unless, you like Batch/PowerShell scripts, which I won't provide out of the box (again, I'm not a Windows guy), then you can also use to manually run them.

If you need any other help, you can find my E-Mail address and other additional Contact Information on my [GitHub Home Page](https://github.com/BeChris100).

Best regards,
BC100Dev (Christoph)
Osintgram4j Maintainer

**Closed** 2024-04-20 16:39 UTC

**Comment by SayanDas74** [comment] 2024-06-26 21:00
You explained all about installation, but how to run the thing? How to login to my ig how to set target etc?

**Comment by radeonxy** [comment] 2024-06-27 03:17
i tried to run the java code but didn't know which .java file to run also

**Comment by BeChris100** [comment] 2024-06-27 06:39
> i tried to run the java code but didn't know which .java file to run also

Because there are Shell scripts that automates things
